
# Short reads discordant sites exploration

rule all:
    input:
        "results/alldatamerged"



rule extract_data:
    input:
        sites = "resources/sites_files_full.fofn",
        samples = "resources/samples_files_full.fofn"

    output:
        directory("results/sites_explored")
    
    conda:
        "envs/biopio.yaml"

    shell:
        "python workflow/scripts/cram_explorer.py {input.sites} {input.samples} {output}"

rule merge_data:
    input:
        "results/sites_explored"
    output:
        "results/alldatamerged"
    shell:
        "workflow/scripts/merge_data.sh {input} {output}"
